// ─── Let's Do Shots! — guest panels ─────────────────────────────────────────
//
// GENERATED by scripts/shots-art.mjs. Do not edit by hand — re-run the import.
//
// Every guest panel is drawn with an EMPTY speech bubble, and the bubble is in
// a slightly different place on each of the 29 sheets. These are the rectangles
// the game sets its type into, measured off the artwork at import time and
// expressed as fractions of the panel so they survive any later rescaling.

/** A rectangle inside a panel, 0..1 of that panel's own width and height. */
export interface BubbleRect {
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface GuestArt {
  /** File stem under /popup/art/shots/ — `${slug}-order.png` and friends. */
  slug: string;
  /** Ordering their shot, at the top of the stage. */
  order: BubbleRect;
  /** Out of swipes, and still dry. */
  mad: BubbleRect;
  /** Stage cleared, shot in hand. */
  happy: BubbleRect;
}

export const GUESTS: GuestArt[] = [
  {
    slug: "guest-01",
    order: { x: 0.08, y: 0.068, w: 0.741, h: 0.136 },
    mad: { x: 0.092, y: 0.068, w: 0.743, h: 0.136 },
    happy: { x: 0.1, y: 0.068, w: 0.679, h: 0.135 },
  },
  {
    slug: "guest-02",
    order: { x: 0.07, y: 0.083, w: 0.72, h: 0.13 },
    mad: { x: 0.095, y: 0.082, w: 0.698, h: 0.13 },
    happy: { x: 0.098, y: 0.083, w: 0.684, h: 0.13 },
  },
  {
    slug: "guest-03",
    order: { x: 0.064, y: 0.063, w: 0.723, h: 0.136 },
    mad: { x: 0.091, y: 0.063, w: 0.715, h: 0.134 },
    happy: { x: 0.095, y: 0.064, w: 0.691, h: 0.133 },
  },
  {
    slug: "guest-04",
    order: { x: 0.073, y: 0.052, w: 0.754, h: 0.123 },
    mad: { x: 0.104, y: 0.054, w: 0.731, h: 0.123 },
    happy: { x: 0.108, y: 0.053, w: 0.729, h: 0.123 },
  },
  {
    slug: "guest-05",
    order: { x: 0.074, y: 0.085, w: 0.732, h: 0.131 },
    mad: { x: 0.081, y: 0.085, w: 0.728, h: 0.13 },
    happy: { x: 0.078, y: 0.085, w: 0.702, h: 0.131 },
  },
  {
    slug: "guest-06",
    order: { x: 0.064, y: 0.071, w: 0.802, h: 0.129 },
    mad: { x: 0.072, y: 0.073, w: 0.8, h: 0.128 },
    happy: { x: 0.067, y: 0.073, w: 0.776, h: 0.128 },
  },
  {
    slug: "guest-07",
    order: { x: 0.081, y: 0.055, w: 0.743, h: 0.12 },
    mad: { x: 0.097, y: 0.057, w: 0.764, h: 0.119 },
    happy: { x: 0.087, y: 0.055, w: 0.806, h: 0.121 },
  },
  {
    slug: "guest-08",
    order: { x: 0.064, y: 0.052, w: 0.735, h: 0.124 },
    mad: { x: 0.081, y: 0.054, w: 0.747, h: 0.123 },
    happy: { x: 0.076, y: 0.054, w: 0.746, h: 0.123 },
  },
  {
    slug: "guest-09",
    order: { x: 0.073, y: 0.074, w: 0.746, h: 0.14 },
    mad: { x: 0.072, y: 0.073, w: 0.717, h: 0.139 },
    happy: { x: 0.096, y: 0.073, w: 0.701, h: 0.139 },
  },
  {
    slug: "guest-10",
    order: { x: 0.071, y: 0.071, w: 0.714, h: 0.14 },
    mad: { x: 0.073, y: 0.071, w: 0.717, h: 0.14 },
    happy: { x: 0.079, y: 0.071, w: 0.699, h: 0.14 },
  },
  {
    slug: "guest-11",
    order: { x: 0.082, y: 0.075, w: 0.717, h: 0.138 },
    mad: { x: 0.071, y: 0.072, w: 0.711, h: 0.139 },
    happy: { x: 0.087, y: 0.074, w: 0.71, h: 0.139 },
  },
  {
    slug: "guest-12",
    order: { x: 0.07, y: 0.069, w: 0.728, h: 0.135 },
    mad: { x: 0.103, y: 0.069, w: 0.706, h: 0.134 },
    happy: { x: 0.1, y: 0.068, w: 0.693, h: 0.135 },
  },
  {
    slug: "guest-13",
    order: { x: 0.078, y: 0.067, w: 0.722, h: 0.133 },
    mad: { x: 0.099, y: 0.066, w: 0.717, h: 0.133 },
    happy: { x: 0.105, y: 0.066, w: 0.69, h: 0.133 },
  },
  {
    slug: "guest-14",
    order: { x: 0.068, y: 0.069, w: 0.715, h: 0.13 },
    mad: { x: 0.097, y: 0.069, w: 0.706, h: 0.13 },
    happy: { x: 0.097, y: 0.069, w: 0.688, h: 0.13 },
  },
  {
    slug: "guest-15",
    order: { x: 0.069, y: 0.057, w: 0.808, h: 0.122 },
    mad: { x: 0.074, y: 0.06, w: 0.819, h: 0.12 },
    happy: { x: 0.073, y: 0.056, w: 0.838, h: 0.12 },
  },
  {
    slug: "guest-16",
    order: { x: 0.065, y: 0.053, w: 0.775, h: 0.123 },
    mad: { x: 0.092, y: 0.055, w: 0.752, h: 0.122 },
    happy: { x: 0.091, y: 0.054, w: 0.773, h: 0.123 },
  },
  {
    slug: "guest-17",
    order: { x: 0.097, y: 0.063, w: 0.701, h: 0.113 },
    mad: { x: 0.109, y: 0.063, w: 0.715, h: 0.117 },
    happy: { x: 0.113, y: 0.063, w: 0.726, h: 0.116 },
  },
  {
    slug: "guest-18",
    order: { x: 0.063, y: 0.054, w: 0.802, h: 0.123 },
    mad: { x: 0.081, y: 0.055, w: 0.765, h: 0.123 },
    happy: { x: 0.095, y: 0.054, w: 0.771, h: 0.122 },
  },
  {
    slug: "guest-19",
    order: { x: 0.061, y: 0.055, w: 0.721, h: 0.121 },
    mad: { x: 0.089, y: 0.057, w: 0.743, h: 0.12 },
    happy: { x: 0.092, y: 0.057, w: 0.735, h: 0.12 },
  },
  {
    slug: "guest-20",
    order: { x: 0.063, y: 0.053, w: 0.77, h: 0.124 },
    mad: { x: 0.107, y: 0.054, w: 0.751, h: 0.125 },
    happy: { x: 0.128, y: 0.052, w: 0.717, h: 0.127 },
  },
  {
    slug: "guest-21",
    order: { x: 0.077, y: 0.053, w: 0.783, h: 0.117 },
    mad: { x: 0.088, y: 0.054, w: 0.757, h: 0.12 },
    happy: { x: 0.096, y: 0.054, w: 0.766, h: 0.12 },
  },
  {
    slug: "guest-22",
    order: { x: 0.06, y: 0.051, w: 0.799, h: 0.123 },
    mad: { x: 0.1, y: 0.053, w: 0.758, h: 0.126 },
    happy: { x: 0.092, y: 0.051, w: 0.788, h: 0.124 },
  },
  {
    slug: "guest-23",
    order: { x: 0.063, y: 0.066, w: 0.723, h: 0.12 },
    mad: { x: 0.105, y: 0.066, w: 0.682, h: 0.121 },
    happy: { x: 0.103, y: 0.066, w: 0.698, h: 0.12 },
  },
  {
    slug: "guest-24",
    order: { x: 0.045, y: 0.058, w: 0.766, h: 0.117 },
    mad: { x: 0.07, y: 0.058, w: 0.743, h: 0.117 },
    happy: { x: 0.092, y: 0.058, w: 0.735, h: 0.117 },
  },
  {
    slug: "guest-25",
    order: { x: 0.063, y: 0.057, w: 0.701, h: 0.119 },
    mad: { x: 0.122, y: 0.058, w: 0.667, h: 0.117 },
    happy: { x: 0.127, y: 0.058, w: 0.684, h: 0.119 },
  },
  {
    slug: "guest-26",
    order: { x: 0.084, y: 0.062, w: 0.678, h: 0.12 },
    mad: { x: 0.134, y: 0.06, w: 0.679, h: 0.12 },
    happy: { x: 0.123, y: 0.059, w: 0.663, h: 0.117 },
  },
  {
    slug: "guest-27",
    order: { x: 0.065, y: 0.058, w: 0.72, h: 0.115 },
    mad: { x: 0.089, y: 0.059, w: 0.729, h: 0.114 },
    happy: { x: 0.112, y: 0.059, w: 0.72, h: 0.113 },
  },
  {
    slug: "guest-28",
    order: { x: 0.094, y: 0.063, w: 0.648, h: 0.104 },
    mad: { x: 0.159, y: 0.063, w: 0.61, h: 0.105 },
    happy: { x: 0.143, y: 0.063, w: 0.63, h: 0.105 },
  },
  {
    slug: "guest-29",
    order: { x: 0.047, y: 0.064, w: 0.74, h: 0.118 },
    mad: { x: 0.092, y: 0.063, w: 0.699, h: 0.116 },
    happy: { x: 0.096, y: 0.063, w: 0.705, h: 0.119 },
  },
];

export const GUEST_COUNT = GUESTS.length;
